/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    products: Product;
    categories: Category;
    collections: Collection;
    reviews: Review;
    customers: Customer;
    orders: Order;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    menus: Menu;
    impressum: Impressum;
    datenschutzerklaerung: Datenschutzerklaerung;
    robots: Robot;
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    datenschutzerklaerung: DatenschutzerklaerungSelect<false> | DatenschutzerklaerungSelect<true>;
    robots: RobotsSelect<false> | RobotsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Customer & {
        collection: 'customers';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Flexible pages built from reusable blocks, including the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  layout?:
    | (
        | HeroBlock
        | PersonalvermittlungBlock
        | UnternehmenBlock
        | OffeneStellenBlock
        | FaqBlock
        | ContactBlock
        | RichContentBlock
        | CtaBlock
        | ImageBlock
        | BannerBlock
        | AccordionBlock
        | SpacerBlock
        | HtmlBlock
      )[]
    | null;
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heroImage?: (string | null) | Media;
  Heading?: string | null;
  SubHeading?: string | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  hero_link?: {
    label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonalvermittlungBlock".
 */
export interface PersonalvermittlungBlock {
  personalvermittlung_Image?: (string | null) | Media;
  Heading?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'personalvermittlung';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnternehmenBlock".
 */
export interface UnternehmenBlock {
  unternehmenTab: {
    /**
     * Wird als klickbarer Tab angezeigt (z. B. Unternehmen oder Kandidat:innen).
     */
    tabLabel: string;
    topHeading?: string | null;
    topCards?:
      | {
          icon?: (string | null) | Media;
          heading?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaHeading?: string | null;
    ctaText?: string | null;
    ctaLink?: {
      label?: string | null;
      /**
       * z. B. #kontakt oder /#kontakt
       */
      url?: string | null;
      target?: ('_self' | '_blank') | null;
    };
    bottomHeading?: string | null;
    bottomCards?:
      | {
          icon?: (string | null) | Media;
          heading?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  kandidatenTab: {
    /**
     * Wird als klickbarer Tab angezeigt (z. B. Unternehmen oder Kandidat:innen).
     */
    tabLabel: string;
    topHeading?: string | null;
    topCards?:
      | {
          icon?: (string | null) | Media;
          heading?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaHeading?: string | null;
    ctaText?: string | null;
    ctaLink?: {
      label?: string | null;
      /**
       * z. B. #kontakt oder /#kontakt
       */
      url?: string | null;
      target?: ('_self' | '_blank') | null;
    };
    bottomHeading?: string | null;
    bottomCards?:
      | {
          icon?: (string | null) | Media;
          heading?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'unternehmen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffeneStellenBlock".
 */
export interface OffeneStellenBlock {
  offeneStellenImage?: (string | null) | Media;
  heading?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  offeneStellen_link?: {
    label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'offeneStellen';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  enableFAQ?: boolean | null;
  Heading?: string | null;
  FaqContent?:
    | {
        title?: string | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  Heading?: string | null;
  SubHeading?: string | null;
  FormHeading?: string | null;
  DatenschutzerklarungLink?: {
    label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  sumbimtedButtonLabel?: string | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentBlock".
 */
export interface RichContentBlock {
  Gutenberg?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  Gutenberg_html?: string | null;
  Featured_image?: (string | null) | Media;
  type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
  media?: (string | null) | Media;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'richContent';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading?: string | null;
  text?: string | null;
  button?: {
    label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  image: string | Media;
  caption?: string | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'image';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  text: string;
  link?: {
    label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  heading?: string | null;
  items?:
    | {
        title: string;
        content?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordion';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock".
 */
export interface SpacerBlock {
  size?: ('sm' | 'md' | 'lg') | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'spacer';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock".
 */
export interface HtmlBlock {
  html?: string | null;
  /**
   * Spacing, visibility and background for this block.
   */
  settings?: {
    visible?: boolean | null;
    /**
     * Optional HTML id, e.g. kontakt
     */
    anchor?: string | null;
    background?: ('default' | 'white' | 'muted' | 'dark') | null;
    padding?: ('none' | 'sm' | 'md' | 'lg') | null;
    align?: ('left' | 'center') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'html';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  price: number;
  compareAtPrice?: number | null;
  category: string | Category;
  collections?: (string | Collection)[] | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  thumbnail?: (string | null) | Media;
  thumbnailUrl?: string | null;
  imageUrls?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  materials?:
    | {
        material: string;
        id?: string | null;
      }[]
    | null;
  colors?:
    | {
        name: string;
        hex: string;
        id?: string | null;
      }[]
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  specifications?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  dimensions?: {
    width?: string | null;
    depth?: string | null;
    height?: string | null;
    seatHeight?: string | null;
  };
  weight?: string | null;
  maxLoad?: string | null;
  warranty?: string | null;
  stock?: number | null;
  availability?: ('in_stock' | 'out_of_stock' | 'pre_order') | null;
  rating?: number | null;
  reviewCount?: number | null;
  featured?: boolean | null;
  bestSeller?: boolean | null;
  newArrival?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  name: string;
  slug: string;
  description?: string | null;
  image?: (string | null) | Media;
  imageUrl?: string | null;
  parentCategory?: (string | null) | Category;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: string;
  name: string;
  slug: string;
  tagline?: string | null;
  description?: string | null;
  image?: (string | null) | Media;
  imageUrl?: string | null;
  products?: (string | Product)[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: string;
  product: string | Product;
  customerName: string;
  rating: number;
  title: string;
  review: string;
  verifiedPurchase?: boolean | null;
  status?: ('approved' | 'pending' | 'rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  name: string;
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  items?:
    | {
        productName: string;
        productId: string;
        quantity: number;
        unitPrice: number;
        color?: string | null;
        id?: string | null;
      }[]
    | null;
  subtotal: number;
  shipping?: number | null;
  tax?: number | null;
  total: number;
  paymentStatus?: ('pending' | 'paid' | 'failed') | null;
  orderStatus?: ('processing' | 'shipped' | 'delivered' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'collections';
        value: string | Collection;
      } | null)
    | ({
        relationTo: 'reviews';
        value: string | Review;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'customers';
        value: string | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        personalvermittlung?: T | PersonalvermittlungBlockSelect<T>;
        unternehmen?: T | UnternehmenBlockSelect<T>;
        offeneStellen?: T | OffeneStellenBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        richContent?: T | RichContentBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        image?: T | ImageBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        accordion?: T | AccordionBlockSelect<T>;
        spacer?: T | SpacerBlockSelect<T>;
        html?: T | HtmlBlockSelect<T>;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heroImage?: T;
  Heading?: T;
  SubHeading?: T;
  richText?: T;
  hero_link?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PersonalvermittlungBlock_select".
 */
export interface PersonalvermittlungBlockSelect<T extends boolean = true> {
  personalvermittlung_Image?: T;
  Heading?: T;
  description?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UnternehmenBlock_select".
 */
export interface UnternehmenBlockSelect<T extends boolean = true> {
  unternehmenTab?:
    | T
    | {
        tabLabel?: T;
        topHeading?: T;
        topCards?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
        ctaHeading?: T;
        ctaText?: T;
        ctaLink?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
        bottomHeading?: T;
        bottomCards?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
      };
  kandidatenTab?:
    | T
    | {
        tabLabel?: T;
        topHeading?: T;
        topCards?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
        ctaHeading?: T;
        ctaText?: T;
        ctaLink?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
        bottomHeading?: T;
        bottomCards?:
          | T
          | {
              icon?: T;
              heading?: T;
              text?: T;
              id?: T;
            };
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OffeneStellenBlock_select".
 */
export interface OffeneStellenBlockSelect<T extends boolean = true> {
  offeneStellenImage?: T;
  heading?: T;
  description?: T;
  offeneStellen_link?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  enableFAQ?: T;
  Heading?: T;
  FaqContent?:
    | T
    | {
        title?: T;
        richText?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  Heading?: T;
  SubHeading?: T;
  FormHeading?: T;
  DatenschutzerklarungLink?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
      };
  sumbimtedButtonLabel?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichContentBlock_select".
 */
export interface RichContentBlockSelect<T extends boolean = true> {
  Gutenberg?: T;
  Gutenberg_html?: T;
  Featured_image?: T;
  type?: T;
  media?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  text?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  text?: T;
  link?:
    | T
    | {
        label?: T;
        url?: T;
        target?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SpacerBlock_select".
 */
export interface SpacerBlockSelect<T extends boolean = true> {
  size?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HtmlBlock_select".
 */
export interface HtmlBlockSelect<T extends boolean = true> {
  html?: T;
  settings?:
    | T
    | {
        visible?: T;
        anchor?: T;
        background?: T;
        padding?: T;
        align?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sku?: T;
  price?: T;
  compareAtPrice?: T;
  category?: T;
  collections?: T;
  shortDescription?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  thumbnail?: T;
  thumbnailUrl?: T;
  imageUrls?:
    | T
    | {
        url?: T;
        id?: T;
      };
  materials?:
    | T
    | {
        material?: T;
        id?: T;
      };
  colors?:
    | T
    | {
        name?: T;
        hex?: T;
        id?: T;
      };
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  dimensions?:
    | T
    | {
        width?: T;
        depth?: T;
        height?: T;
        seatHeight?: T;
      };
  weight?: T;
  maxLoad?: T;
  warranty?: T;
  stock?: T;
  availability?: T;
  rating?: T;
  reviewCount?: T;
  featured?: T;
  bestSeller?: T;
  newArrival?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  parentCategory?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  image?: T;
  imageUrl?: T;
  products?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  customerName?: T;
  rating?: T;
  title?: T;
  review?: T;
  verifiedPurchase?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  items?:
    | T
    | {
        productName?: T;
        productId?: T;
        quantity?: T;
        unitPrice?: T;
        color?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  tax?: T;
  total?: T;
  paymentStatus?: T;
  orderStatus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  title?: string | null;
  slug?: string | null;
  Header_Logo?: (string | null) | Media;
  Mobile_Header_Logo?: (string | null) | Media;
  link?: {
    Kontakt_label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
  media?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  title?: string | null;
  slug?: string | null;
  footerlogo?: (string | null) | Media;
  description?: string | null;
  social?:
    | {
        social_icon: string | Media;
        social_url: string;
        id?: string | null;
      }[]
    | null;
  kontakt?: {
    phone?: string | null;
    phone_urls?: string | null;
    email?: string | null;
    email_url?: string | null;
    address?: string | null;
    address_url?: string | null;
  };
  sprechzeiten?:
    | {
        day?: string | null;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  navigation?:
    | {
        heading: string;
        menus?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  menus?:
    | {
        link?: {
          label?: string | null;
          url?: string | null;
          target?: ('_self' | '_blank') | null;
        };
        submenus?:
          | {
              links?:
                | {
                    link?: {
                      label?: string | null;
                      url?: string | null;
                      target?: ('_self' | '_blank') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: string;
  title?: string | null;
  slug: string;
  contents?: {
    Gutenberg?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    Gutenberg_html?: string | null;
    Featured_image?: (string | null) | Media;
    type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
    media?: (string | null) | Media;
  };
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutzerklaerung".
 */
export interface Datenschutzerklaerung {
  id: string;
  title?: string | null;
  slug: string;
  contents?: {
    Gutenberg?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    Gutenberg_html?: string | null;
    Featured_image?: (string | null) | Media;
    type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
    media?: (string | null) | Media;
  };
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots".
 */
export interface Robot {
  id: string;
  robots?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName?: string | null;
  tagline?: string | null;
  email?: string | null;
  phone?: string | null;
  address?: string | null;
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  hero?: {
    badge?: string | null;
    heading?: string | null;
    headingAccent?: string | null;
    description?: string | null;
    imageUrl?: string | null;
    primaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    metrics?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  categoriesSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  productsSection?: {
    eyebrow?: string | null;
    heading?: string | null;
    linkLabel?: string | null;
    linkUrl?: string | null;
  };
  whyChoose?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    items?:
      | {
          title: string;
          description: string;
          icon?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  ergo?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaUrl?: string | null;
    tabs?:
      | {
          key: string;
          title: string;
          description?: string | null;
          imageUrl?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  collectionsSection?: {
    eyebrow?: string | null;
    heading?: string | null;
  };
  testimonials?: {
    eyebrow?: string | null;
    heading?: string | null;
    items?:
      | {
          quote: string;
          author: string;
          role?: string | null;
          rating?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    eyebrow?: string | null;
    heading?: string | null;
    description?: string | null;
    primaryCta?: {
      label?: string | null;
      url?: string | null;
    };
    secondaryCta?: {
      label?: string | null;
      url?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  heroEyebrow?: string | null;
  heroHeading?: string | null;
  heroDescription?: string | null;
  storyEyebrow?: string | null;
  storyHeading?: string | null;
  storyParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  storyImageUrl?: string | null;
  pillarsHeading?: string | null;
  pillars?:
    | {
        icon?: string | null;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaHeading?: string | null;
  ctaLabel?: string | null;
  ctaUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  Header_Logo?: T;
  Mobile_Header_Logo?: T;
  link?:
    | T
    | {
        Kontakt_label?: T;
        url?: T;
        target?: T;
      };
  type?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  footerlogo?: T;
  description?: T;
  social?:
    | T
    | {
        social_icon?: T;
        social_url?: T;
        id?: T;
      };
  kontakt?:
    | T
    | {
        phone?: T;
        phone_urls?: T;
        email?: T;
        email_url?: T;
        address?: T;
        address_url?: T;
      };
  sprechzeiten?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        heading?: T;
        menus?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  menus?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
        submenus?:
          | T
          | {
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          target?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contents?:
    | T
    | {
        Gutenberg?: T;
        Gutenberg_html?: T;
        Featured_image?: T;
        type?: T;
        media?: T;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutzerklaerung_select".
 */
export interface DatenschutzerklaerungSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contents?:
    | T
    | {
        Gutenberg?: T;
        Gutenberg_html?: T;
        Featured_image?: T;
        type?: T;
        media?: T;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots_select".
 */
export interface RobotsSelect<T extends boolean = true> {
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  address?: T;
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        heading?: T;
        headingAccent?: T;
        description?: T;
        imageUrl?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        metrics?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  categoriesSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  productsSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        linkLabel?: T;
        linkUrl?: T;
      };
  whyChoose?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              icon?: T;
              id?: T;
            };
      };
  ergo?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaUrl?: T;
        tabs?:
          | T
          | {
              key?: T;
              title?: T;
              description?: T;
              imageUrl?: T;
              id?: T;
            };
      };
  collectionsSection?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              quote?: T;
              author?: T;
              role?: T;
              rating?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroHeading?: T;
  heroDescription?: T;
  storyEyebrow?: T;
  storyHeading?: T;
  storyParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  storyImageUrl?: T;
  pillarsHeading?: T;
  pillars?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  ctaHeading?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}