/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    header: Header;
    footer: Footer;
    menus: Menu;
    home: Home;
    impressum: Impressum;
    datenschutzerklaerung: Datenschutzerklaerung;
    robots: Robot;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    impressum: ImpressumSelect<false> | ImpressumSelect<true>;
    datenschutzerklaerung: DatenschutzerklaerungSelect<false> | DatenschutzerklaerungSelect<true>;
    robots: RobotsSelect<false> | RobotsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  title?: string | null;
  slug?: string | null;
  Header_Logo?: (string | null) | Media;
  Mobile_Header_Logo?: (string | null) | Media;
  link?: {
    Kontakt_label?: string | null;
    url?: string | null;
    target?: ('_self' | '_blank') | null;
  };
  type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
  media?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  title?: string | null;
  slug?: string | null;
  footerlogo?: (string | null) | Media;
  description?: string | null;
  social?:
    | {
        social_icon: string | Media;
        social_url: string;
        id?: string | null;
      }[]
    | null;
  kontakt?: {
    phone?: string | null;
    phone_urls?: string | null;
    email?: string | null;
    email_url?: string | null;
    address?: string | null;
    address_url?: string | null;
  };
  sprechzeiten?:
    | {
        day?: string | null;
        time?: string | null;
        id?: string | null;
      }[]
    | null;
  navigation?:
    | {
        heading: string;
        menus?:
          | {
              label: string;
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: string;
  menus?:
    | {
        link?: {
          label?: string | null;
          url?: string | null;
          target?: ('_self' | '_blank') | null;
        };
        submenus?:
          | {
              links?:
                | {
                    link?: {
                      label?: string | null;
                      url?: string | null;
                      target?: ('_self' | '_blank') | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: string;
  title?: string | null;
  author?: (string | null) | User;
  slug: string;
  hero?: {
    heroImage?: (string | null) | Media;
    Heading?: string | null;
    SubHeading?: string | null;
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    hero_link?: {
      label?: string | null;
      url?: string | null;
      target?: ('_self' | '_blank') | null;
    };
  };
  personalvermittlung?: {
    personalvermittlung_Image?: (string | null) | Media;
    Heading?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  unternehmen?: {
    link_title?:
      | {
          title?: {
            label?: string | null;
          };
          sub_title?:
            | {
                links?:
                  | {
                      label?: string | null;
                      sliderHeading?: string | null;
                      slider?:
                        | {
                            'Slider Item'?:
                              | {
                                  sliderImage?: (string | null) | Media;
                                  Heading?: string | null;
                                  richText?: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  } | null;
                                  id?: string | null;
                                }[]
                              | null;
                            'CTA Item'?:
                              | {
                                  CTAHeading?: string | null;
                                  richText?: {
                                    root: {
                                      type: string;
                                      children: {
                                        type: any;
                                        version: number;
                                        [k: string]: unknown;
                                      }[];
                                      direction: ('ltr' | 'rtl') | null;
                                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                                      indent: number;
                                      version: number;
                                    };
                                    [k: string]: unknown;
                                  } | null;
                                  CTA_link?: {
                                    label?: string | null;
                                    url?: string | null;
                                    target?: ('_self' | '_blank') | null;
                                  };
                                  id?: string | null;
                                }[]
                              | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                    }[]
                  | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    Sub_link_title?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  offeneStellen?: {
    offeneStellenImage?: (string | null) | Media;
    heading?: string | null;
    description?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    offeneStellen_link?: {
      label?: string | null;
      url?: string | null;
      target?: ('_self' | '_blank') | null;
    };
  };
  FaqSection?: {
    enableFAQ?: boolean | null;
    Heading?: string | null;
    FaqContent?:
      | {
          title?: string | null;
          richText?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          id?: string | null;
        }[]
      | null;
  };
  kontakt?: {
    Heading?: string | null;
    SubHeading?: string | null;
    FormHeading?: string | null;
    DatenschutzerklarungLink?: {
      label?: string | null;
      url?: string | null;
      target?: ('_self' | '_blank') | null;
    };
    sumbimtedButtonLabel?: string | null;
  };
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum".
 */
export interface Impressum {
  id: string;
  title?: string | null;
  slug: string;
  contents?: {
    Gutenberg?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    Gutenberg_html?: string | null;
    Featured_image?: (string | null) | Media;
    type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
    media?: (string | null) | Media;
  };
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutzerklaerung".
 */
export interface Datenschutzerklaerung {
  id: string;
  title?: string | null;
  slug: string;
  contents?: {
    Gutenberg?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    Gutenberg_html?: string | null;
    Featured_image?: (string | null) | Media;
    type?: ('none' | 'highImpact' | 'mediumImpact' | 'lowImpact') | null;
    media?: (string | null) | Media;
  };
  seo?: {
    meta?: {
      title?: string | null;
      description?: string | null;
      /**
       * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
       */
      image?: (string | null) | Media;
      /**
       * Enter your JSON-LD schema markup here. This is typically used for rich snippets.
       */
      schemaMarkup?: string | null;
      indexing?: ('index' | 'noindex') | null;
      following?: ('follow' | 'nofollow') | null;
      canonicalUrl?: string | null;
    };
  };
  publishedAt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots".
 */
export interface Robot {
  id: string;
  robots?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  Header_Logo?: T;
  Mobile_Header_Logo?: T;
  link?:
    | T
    | {
        Kontakt_label?: T;
        url?: T;
        target?: T;
      };
  type?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  footerlogo?: T;
  description?: T;
  social?:
    | T
    | {
        social_icon?: T;
        social_url?: T;
        id?: T;
      };
  kontakt?:
    | T
    | {
        phone?: T;
        phone_urls?: T;
        email?: T;
        email_url?: T;
        address?: T;
        address_url?: T;
      };
  sprechzeiten?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        heading?: T;
        menus?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  menus?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
        submenus?:
          | T
          | {
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                          target?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  slug?: T;
  hero?:
    | T
    | {
        heroImage?: T;
        Heading?: T;
        SubHeading?: T;
        richText?: T;
        hero_link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
      };
  personalvermittlung?:
    | T
    | {
        personalvermittlung_Image?: T;
        Heading?: T;
        description?: T;
      };
  unternehmen?:
    | T
    | {
        link_title?:
          | T
          | {
              title?:
                | T
                | {
                    label?: T;
                  };
              sub_title?:
                | T
                | {
                    links?:
                      | T
                      | {
                          label?: T;
                          sliderHeading?: T;
                          slider?:
                            | T
                            | {
                                'Slider Item'?:
                                  | T
                                  | {
                                      sliderImage?: T;
                                      Heading?: T;
                                      richText?: T;
                                      id?: T;
                                    };
                                'CTA Item'?:
                                  | T
                                  | {
                                      CTAHeading?: T;
                                      richText?: T;
                                      CTA_link?:
                                        | T
                                        | {
                                            label?: T;
                                            url?: T;
                                            target?: T;
                                          };
                                      id?: T;
                                    };
                                id?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        Sub_link_title?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  offeneStellen?:
    | T
    | {
        offeneStellenImage?: T;
        heading?: T;
        description?: T;
        offeneStellen_link?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
      };
  FaqSection?:
    | T
    | {
        enableFAQ?: T;
        Heading?: T;
        FaqContent?:
          | T
          | {
              title?: T;
              richText?: T;
              id?: T;
            };
      };
  kontakt?:
    | T
    | {
        Heading?: T;
        SubHeading?: T;
        FormHeading?: T;
        DatenschutzerklarungLink?:
          | T
          | {
              label?: T;
              url?: T;
              target?: T;
            };
        sumbimtedButtonLabel?: T;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "impressum_select".
 */
export interface ImpressumSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contents?:
    | T
    | {
        Gutenberg?: T;
        Gutenberg_html?: T;
        Featured_image?: T;
        type?: T;
        media?: T;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datenschutzerklaerung_select".
 */
export interface DatenschutzerklaerungSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  contents?:
    | T
    | {
        Gutenberg?: T;
        Gutenberg_html?: T;
        Featured_image?: T;
        type?: T;
        media?: T;
      };
  seo?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
              image?: T;
              schemaMarkup?: T;
              indexing?: T;
              following?: T;
              canonicalUrl?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "robots_select".
 */
export interface RobotsSelect<T extends boolean = true> {
  robots?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}